function [nssTraces,sscsTraces,ssncsTraces,badapl,blMean]=comp_multiresp(data,options)
% computes average response to different alignments and trial types
% also outputs individual trial activity for saccade and baseline epochs

if exist('options','var')
    sigma=options.sigma;
    baselineLength=options.baselineLength;
    short_wds=options.short_wds;
    short_wde=options.short_wde;
    long_wds=options.long_wds;
else
    sigma=10;
    baselineLength=500;
    short_wds=200;
    short_wde=199;
    long_wds=600;
end

if ~options.blNorm
    %% no-stop signal trials
    % [nssTraces.baseline]=cellfun(@(x) conv_raster(x(1,1).rast,sigma,...
    %     0,x(1,1).alignt-(long_wds+sigma*3),x(1,1).alignt+(sigma*3-1)),...
    %     data.allndata(:,2), 'UniformOutput',false);
    nssTraces.saccade=cellfun(@(x) conv_raster(x(1,1).rast,sigma,...
        0,x(1,1).alignt-(long_wds+sigma*3),x(1,1).alignt+(short_wde+sigma*3)),...
        data.allndata(:,1), 'UniformOutput',false); % vs sac
    nssTraces.target=cellfun(@(x) conv_raster(x(1,1).rast,sigma,...
        0,x(1,1).alignt-(long_wds+sigma*3),x(1,1).alignt+(short_wde+sigma*3)),...
        data.allndata(:,2), 'UniformOutput',false);% vs target
    nssTraces.stopsignal=cellfun(@(x) conv_raster(x(1,1).rast,sigma,...
        0,x(1,1).alignt-(long_wds+sigma*3),x(1,1).alignt+(short_wde+sigma*3)),...
        data.allndata(:,3), 'UniformOutput',false);% vs stop signal
    nssTraces.reward=cellfun(@(x) conv_raster(x(1,1).rast,sigma,...
        0,x(1,1).alignt-(long_wds+sigma*3),x(1,1).alignt+(short_wde+sigma*3)),...
        data.allndata(:,5), 'UniformOutput',false);% vs reward
    
    %% stop signal trials with canceled saccades
    % [sscsTraces.baseline]=cellfun(@(x) conv_raster(x(2).rast,sigma,...
    %     0,x(2).alignt-(long_wds+sigma*3),x(2).alignt+(sigma*3-1)),...
    %     data.allndata(:,2), 'UniformOutput',false); % baseline
    sscsTraces.saccade=cellfun(@(x) conv_raster(x(2).rast,sigma,...
        0,x(2).alignt-(long_wds+sigma*3),x(2).alignt+(short_wde+sigma*3)),...
        data.allndata(:,1), 'UniformOutput',false); % vs sac
    sscsTraces.target=cellfun(@(x) conv_raster(x(2).rast,sigma,...
        0,x(2).alignt-(long_wds+sigma*3),x(2).alignt+(short_wde+sigma*3)),...
        data.allndata(:,2), 'UniformOutput',false); % vs target
    sscsTraces.stopsignal=cellfun(@(x) conv_raster(x(3).rast,sigma,...
        0,x(3).alignt-(long_wds+sigma*3),x(3).alignt+(short_wde+sigma*3)),...
        data.allndata(:,3), 'UniformOutput',false); % vs stop signal
    sscsTraces.reward=cellfun(@(x) conv_raster(x(2).rast,sigma,...
        0,x(2).alignt-(long_wds+sigma*3),x(2).alignt+(short_wde+sigma*3)),...
        data.allndata(:,5), 'UniformOutput',false); % vs reward
    
    %% stop signal trials with non-canceled saccades
    badapl=(cellfun(@(x) size({x.rast},2),data.allndata(:,1))<3);
    % [ssncsTraces.baseline]=cellfun(@(x) conv_raster(x(3).rast,sigma,...
    %     0,x(3).alignt-(long_wds+sigma*3),x(3).alignt+(sigma*3-1)),...
    %     data.allndata(:,2), 'UniformOutput',false); % baseline
    ssncsTraces.saccade=cellfun(@(x) conv_raster(x(3).rast,sigma,...
        0,x(3).alignt-(long_wds+sigma*3),x(3).alignt+(short_wde+sigma*3)),...
        data.allndata(~badapl,1), 'UniformOutput',false); % vs sac
    ssncsTraces.target=cellfun(@(x) conv_raster(x(3).rast,sigma,...
        0,x(3).alignt-(long_wds+sigma*3),x(3).alignt+(short_wde+sigma*3)),...
        data.allndata(~badapl,2), 'UniformOutput',false); % vs target
    ssncsTraces.stopsignal=cellfun(@(x) conv_raster(x(4).rast,sigma,...
        0,x(4).alignt-(long_wds+sigma*3),x(4).alignt+(short_wde+sigma*3)),...
        data.allndata(~badapl,3), 'UniformOutput',false); % vs stop signal
    ssncsTraces.reward=cellfun(@(x) conv_raster(x(3).rast,sigma,...
        0,x(3).alignt-(long_wds+sigma*3),x(3).alignt+(short_wde+sigma*3)),...
        data.allndata(~badapl,5), 'UniformOutput',false); % vs reward
    
    
    
    %% Normalization (baseline substracted)
else
        blMean=cellfun(@(x) mean(conv_raster(x(1,1).rast,sigma,...
        0,x(1,1).alignt-(baselineLength+sigma*3),x(1,1).alignt+(sigma*3-1))),...
        data(:,2), 'UniformOutput',false);
        blMean(:,2)=cellfun(@(rasterData) mean(conv_raster(rasterData(2).rast,sigma,...
        0,rasterData(2).alignt-(baselineLength+sigma*3),rasterData(2).alignt+(sigma*3-1))),...
        data(:,2),'UniformOutput',false); 
        blMean(:,3)=cellfun(@(rasterData) mean(conv_raster(rasterData(3).rast,sigma,...
        0,rasterData(3).alignt-(baselineLength+sigma*3),rasterData(3).alignt+(sigma*3-1))),...
        data(:,2), 'UniformOutput',false);
        blMean=cellfun(@(x,y,z) nanmean([x,y,z]), blMean(:,1),blMean(:,2),blMean(:,3), 'UniformOutput',false);

%     nssTraces.blMean=cellfun(@(x) mean(conv_raster(x(1,1).rast,sigma,...
%         0,x(1,1).alignt-(long_wds+sigma*3),x(1,1).alignt+(sigma*3-1))),...
%         data(:,2), 'UniformOutput',false);
    nssTraces.saccade=cellfun(@(rasterData,blAverage) conv_raster(rasterData(1,1).rast,sigma,...
        0,rasterData(1,1).alignt-(long_wds+sigma*3),rasterData(1,1).alignt+(short_wde+sigma*3))-blAverage,...
        data(:,1),blMean, 'UniformOutput',false); % vs sac
    nssTraces.target=cellfun(@(rasterData,blAverage) conv_raster(rasterData(1,1).rast,sigma,...
        0,rasterData(1,1).alignt-(long_wds+sigma*3),rasterData(1,1).alignt+(short_wde+sigma*3))-blAverage,...
        data(:,2),blMean, 'UniformOutput',false);% vs target
    nssTraces.stopsignal=cellfun(@(rasterData,blAverage) conv_raster(rasterData(1,1).rast,sigma,...
        0,rasterData(1,1).alignt-(long_wds+sigma*3),rasterData(1,1).alignt+(short_wde+sigma*3))-blAverage,...
        data(:,3),blMean, 'UniformOutput',false);% vs stop signal
    nssTraces.reward=cellfun(@(rasterData,blAverage) conv_raster(rasterData(1,1).rast,sigma,...
        0,rasterData(1,1).alignt-(long_wds+sigma*3),rasterData(1,1).alignt+(short_wde+sigma*3))-blAverage,...
        data(:,5),blMean, 'UniformOutput',false);% vs reward
    
    %% stop signal trials with canceled saccades
%     sscsTraces.blMean=cellfun(@(rasterData) mean(conv_raster(rasterData(2).rast,sigma,...
%         0,rasterData(2).alignt-(long_wds+sigma*3),rasterData(2).alignt+(sigma*3-1))),...
%         data(:,2),'UniformOutput',false); % baseline
    sscsTraces.saccade=cellfun(@(rasterData,blAverage) conv_raster(rasterData(2).rast,sigma,...
        0,rasterData(2).alignt-(long_wds+sigma*3),rasterData(2).alignt+(short_wde+sigma*3))-blAverage,...
        data(:,1),blMean, 'UniformOutput',false); % vs sac
    sscsTraces.target=cellfun(@(rasterData,blAverage) conv_raster(rasterData(2).rast,sigma,...
        0,rasterData(2).alignt-(long_wds+sigma*3),rasterData(2).alignt+(short_wde+sigma*3))-blAverage,...
        data(:,2),blMean, 'UniformOutput',false); % vs target
    sscsTraces.stopsignal=cellfun(@(rasterData,blAverage) conv_raster(rasterData(3).rast,sigma,...
        0,rasterData(3).alignt-(long_wds+sigma*3),rasterData(3).alignt+(short_wde+sigma*3))-blAverage,...
        data(:,3),blMean, 'UniformOutput',false); % vs stop signal
    sscsTraces.reward=cellfun(@(rasterData,blAverage) conv_raster(rasterData(2).rast,sigma,...
        0,rasterData(2).alignt-(long_wds+sigma*3),rasterData(2).alignt+(short_wde+sigma*3))-blAverage,...
        data(:,5),blMean, 'UniformOutput',false); % vs reward
    
    %% stop signal trials with non-canceled saccades
    badapl=(cellfun(@(rasterData) size({rasterData.rast},2),data(:,1))<3);
%     ssncsTraces.blMean=cellfun(@(rasterData) mean(conv_raster(rasterData(3).rast,sigma,...
%         0,rasterData(3).alignt-(long_wds+sigma*3),rasterData(3).alignt+(sigma*3-1))),...
%         data(:,2), 'UniformOutput',false); % baseline
    ssncsTraces.saccade=cellfun(@(rasterData,blAverage) conv_raster(rasterData(3).rast,sigma,...
        0,rasterData(3).alignt-(long_wds+sigma*3),rasterData(3).alignt+(short_wde+sigma*3))-blAverage,...
        data(~badapl,1),blMean(~badapl), 'UniformOutput',false); % vs sac
    ssncsTraces.target=cellfun(@(rasterData,blAverage) conv_raster(rasterData(3).rast,sigma,...
        0,rasterData(3).alignt-(long_wds+sigma*3),rasterData(3).alignt+(short_wde+sigma*3))-blAverage,...
        data(:,2),blMean, 'UniformOutput',false); % vs target
    ssncsTraces.stopsignal=cellfun(@(rasterData,blAverage) conv_raster(rasterData(4).rast,sigma,...
        0,rasterData(4).alignt-(long_wds+sigma*3),rasterData(4).alignt+(short_wde+sigma*3))-blAverage,...
        data(:,3),blMean, 'UniformOutput',false); % vs stop signal
    ssncsTraces.reward=cellfun(@(rasterData,blAverage) conv_raster(rasterData(3).rast,sigma,...
        0,rasterData(3).alignt-(long_wds+sigma*3),rasterData(3).alignt+(short_wde+sigma*3))-blAverage,...
        data(:,5),blMean, 'UniformOutput',false); % vs reward
    
    
    %     fieldNames={'saccade';'target';'stopsignal';'reward'};
    %     baseline=vertcat(nssTraces.baseline{:}); %,...
    %     %         sscsTraces.baseline{:}, ssncsTraces.baseline{:});
    %     blRespMean=nanmean(baseline,2);
    %     % blRespSD=nanstd(nssResps.baseline,[],2);
    %     for fn=[1,2,4]
    %         (fieldNames{fn})=mat2cell(vertcat(...
    %             nssTraces.(fieldNames{fn}){:})-blRespMean,ones(100,1));
    %     end
    %     for fn=[2,3,4]
    %         sscsTraces.(fieldNames{fn})=mat2cell(...
    %             vertcat(sscsTraces.(fieldNames{fn}){:})-blRespMean,ones(100,1));
    %     end
    %     for fn=[1,2,3]
    %         ssncsTraces.(fieldNames{fn})=mat2cell(...
    %             vertcat(ssncsTraces.(fieldNames{fn}){:})-blRespMean(~badapl),ones(99,1));
    %     end
end

%% cells with not enough data in one of the conditions
badapl=cellfun(@(x,y,z,u,v,w,s,t) size(x,2)==1 || size(y,2)==1 || size(z,2)==1 ||...
    size(u,2)==1 || size(v,2)==1 || size(w,2)==1 || size(s,2)==1 || size(t,2)==1, ...
    nssTraces.saccade, nssTraces.target, nssTraces.reward, sscsTraces.target,...
    sscsTraces.stopsignal, sscsTraces.reward, nssTraces.stopsignal, sscsTraces.saccade)...
    | badapl;